name: Build Impersonate EXE
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Find and Build Solution
        shell: pwsh
        run: |
          # Find the first .sln file in the repo
          $slnFile = Get-ChildItem -Recurse -Filter "Impersonate.sln" | Select-Object -First 1 -ExpandProperty FullName
          Write-Host "Found Solution at: $slnFile"
          
          # Run MSBuild on the specific path found
          msbuild $slnFile /p:Configuration=Release /p:Platform=x64 /p:RuntimeLibrary=MultiThreaded

      - name: Upload Compiled EXE
        uses: actions/upload-artifact@v4
        with:
          name: Impersonate-x64-Static
          path: "**/Release/*.exe"
